### ISSUE TITLE
Allow user to refresh commit graph when detects local repo changes

### ISSUE THREAD

**Issue by SiRumCz** [uvicgse/project-virtual-team-1#105]
Commit graph can auto detects changes in the repo and allow user to refresh graph manually.

**Comment by sterlinglaird** [comment]
Because we already have multiple live reload checks (for file changes and branch/tag updates), it might be worth combining all of the periodic checks into a single check which updates everything in the GUI that needs to be changed.

**Comment by SiRumCz** [comment]
I combined three cheks here into a single monitor to do 3 seconds a check.
```
// group all monitors here, call every 3 seconds
  setInterval(function() {
    // Update modified files on left file panel
    displayModifiedFiles();
    // monitor changes on branch list and tag list
    refreshList(false);
    // check if there is any changes to either ref list or commits
    checkCommitChange();
  }, 3000);
```

**Comment by SiRumCz** [comment]
After my investigation and implementation, I have two concerns for this feature:
1. User will have a great chance running into white node problem when try to refresh graph. 
2. When new commits have been made, after user refreshed the commit graph, the pointing branch will still be pointed to old commit(instead of new commit that just been made).
The first problem is under investigation by @sterlinglaird for this sprint. But for the second problem I am not sure why it doesn't update pointing commit.
