### ISSUE TITLE
Factor out navbar from Pull Request slider

### ISSUE THREAD

**Issue by nikola-rados** [uvicgse/project-virtual-team-1#109]
We would like to use the sidebar where the current PR button is for the rebasing button as well (and likely future buttons). That would mean decoupling the slide out menu from the button itself and populating the menu depending on which button is pushed.

This issue is a sub-issue of #35.

**Comment by Athenasko** [comment]
Discussed with @nikola-rados and after some paired programming have decided the Pull Request bar is too hard-coded to be able to factor it out into a useable Sidebar for the Rebasing feature. 
As such, this ticket is not going to be used, and the rebase feature bar will just be worked on in #110.
