### ISSUE TITLE
Add interactive Rebase UI options

### ISSUE THREAD

**Issue by nikola-rados** [uvicgse/project-virtual-team-1#111]
Add a table that would show each commit and have options for what to do with that commit (squash, pick, reword) as a part of the Rebase UI.

This is a sub-issue of #35.

**Comment by aeogunmuyiwa** [comment]
Currently I have included a commit list pop up on rebase click which shows the commits. on branch feature-110-rebase-ui-popup-fresh

**Comment by aeogunmuyiwa** [comment]
the link below contains images of the feature https://slack-files.com/TJBDCRM6G-FKM8JENTE-e3e69305d0
https://slack-files.com/TJBDCRM6G-FKPSN8L8N-721b562780 
https://slack-files.com/TJBDCRM6G-FKMNMBK6U-1eb49a5180
