### ISSUE TITLE
Add basic Rebase functionality

### ISSUE THREAD

**Issue by nikola-rados** [uvicgse/project-virtual-team-1#112]
Add some basic functionality to rebase.  Have the user choose the branch they want to rebase onto and perform the rebase only if there are no merge conflicts (otherwise just abort).

This is a sub-issue of #35.

**Comment by aeogunmuyiwa** [comment]
<img width="1183" alt="Screen Shot 2019-06-20 at 11 04 24 AM" src="https://user-images.githubusercontent.com/25914907/59870890-34d95780-934b-11e9-8b76-3ab497cb8b15.png">
Fixed the onto drop down list , I had to adjust how the options tag was created and call the function in the div

**Comment by Athenasko** [comment]
Merged into master.
