### ISSUE TITLE
Handling Merge conflicts

### ISSUE THREAD

**Issue by nikola-rados** [uvicgse/project-virtual-team-1#113]
During a rebase, show a list of the files causing the conflicts and add a button that would open them for the user in the file editor.

This is a sub-issue of #35.

**Comment by Unimax** [comment]
Create a merged file @ local by VisualGIt Steps:-
1. commit a change in a local repo, for example, sample.txt line 2 & 3
2. now open the remote repo in github.com and commit a change in the same file at the same lines (to create conflicts)
3. Open repo using visual git and pull. after pulling you can see the file have both changes from local and remote. changes can be seen in visual git also. (this mean it has a feature to create such  merge conflict)
4. Pull will now specify which fills have unresolved conflicts with a filename. (that mean it has a feature to detect)

![confilit](https://user-images.githubusercontent.com/4117562/59393511-cb48c000-8d30-11e9-9d88-9771469826ba.JPG)


so this mean visual git can created merged files.
this also mean it can detect file with merge conflits.

need to figure out which part of the code do this.

**Comment by trstndvll** [comment]
So as of now, handling merge conflicts only works on pull, and isn't used in the rebasing functionality. The way merge conflicts are handled now are very similar to how git handles conflicts, by showing you the files and linking to your IDE. This issue should be handled in the future depending on what sort of functionality the PO wants, and how they want it to work with rebase.
