### ISSUE TITLE
The navbar icons flicker as you mouse over them

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#130]
if you mouse over the icons, you can see them resize and adjust. While this is a cosmetic issue, it does not look very good for something that is a key component to this

**Comment by maxUser** [comment]
I've turned this into more of an overhaul of the icons and login/out buttons.

**Comment by colinwerner** [comment]
closing on behalf of @maxUser, please re-open if you feel necessary.
