### ISSUE TITLE
VisualGit merge conflict support (On pull)

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#142]
Problem
VisualGit doesn't give support for resolving merge conflicts on a pull from the remote.

Task
A clear message should be provided when the merge conflict occurs.
The message should list which files contain the conflicts and give a method to easily open the files.

Research
Research further ways in which visualGit can support easy resolution of merge conflicts.
Look at ways other tools support this.

**Comment by colinwerner** [comment]
https://github.com/uvicgse/project-seed/issues/55

**Comment by Unimax** [comment]
Create a merged file @ local by VisualGIt Steps:-
1. commit a change in a local repo, for example, sample.txt line 2 & 3
2. now open the remote repo in github.com and commit a change in the same file at the same lines (to create conflicts)
3. Open repo using visual git and pull. after pulling you can see the file have both changes from local and remote. changes can be seen in visual git also. (this mean it has a feature to create such  merge conflict)
4. Pull will now specify which fills have unresolved conflicts with a filename. (that mean it has a feature to detect)

the above step do create merge conflicts!! and Visual git let you know about them

**Comment by trstndvll** [comment]
Closed as this is covered in #113 .
