### ISSUE TITLE
Commit Signature Based on Username instead of Oauth Application

### ISSUE THREAD

**Issue by dragonprevost** [uvicgse/project-virtual-team-1#145]
When generating commits in the VisualGit App, signatures are created using `repo.defaultSignature()`. Since sessions are authenticated using Oauth, commits appear to come from the application instead of the user. 

For example if tommy changes a file and commits it via Visual Git, it would appear that a commit came from VisualGit instead of user 'tommy' when pushing via access tokens.

Signatures can be generated using `var signature = Signature.create(name, email, time, offset);` Documentation is found [here](https://www.nodegit.org/api/signature/)

By replacing the signature `sign = repository.defaultSignature();` with the Signature above the commits should be signed by the correct user.

**Comment by colinwerner** [comment]
This signature is used in many places. Should we adjust it everywhere? (I believe we use it in stashing...)

**Comment by dragonprevost** [comment]
> This signature is used in many places. Should we adjust it everywhere? (I believe we use it in stashing...)

Yeah great idea, I have created a function in authenticate.ts to return a signature object based on the user that has signed in. You can checkout those changes [here](https://github.com/uvicgse/project-virtual-team-1/pull/154). I believe all the stash functions that rely on a signature have been updated but take a look to double check.
