### ISSUE TITLE
Add drag and drop functionality to graph

### ISSUE THREAD

**Issue by hdauvic** [uvicgse/project-virtual-team-1#148]
Add drag and drop functionality from stashes to the graph. Ideally, the ability to drag a stash from the list directly onto the graph would add a node to the graph, update the repo, and update the stash.

This new feature is linked to issues #144 and #126 .

May also be updated in the future to add the ability of drag and drop to commits/branches/tags.

**Comment by Unimax** [comment]
i think dragging stash into unchanged files makes more sence.

**Comment by hdauvic** [comment]
I agree, however, this was something Kelly mentioned she wanted functionality of during the demos.

**Comment by SiRumCz** [comment]
I thought this feature was implemented in the sprint 4.

**Comment by colinwerner** [comment]
Closing as we did this.
