### ISSUE TITLE
Add stashes to the graph

### ISSUE THREAD

**Issue by hdauvic** [uvicgse/project-virtual-team-1#149]
Add a visual component to the stash function by adding nodes to the graph.

Likely related to #144

**Comment by SiRumCz** [comment]
After spending hours on researching and had several meetings regarding the topic of git stashing, I don't think the stash list can be added to the graph as it is not related to any commit and the state of stash list is completely independent and isolated to the graph. I will stop my work on this issue until I get answers back from James.
