### ISSUE TITLE
Highlight un-pushed commit nodes on graph

### ISSUE THREAD

**Issue by trstndvll** [uvicgse/project-virtual-team-1#150]
Currently, you cannot distinguish nodes on the graph that are un-pushed (i.e. not on remote). This issue would be looking into seeing if the newly-integrated simple-git would allow us to find the commit IDs that are not pushed, and highlight the nodes corresponding to those IDs in the graph.

**Comment by trstndvll** [comment]
Not sure if I completely understand this fully, but it looks like you can specify "options" in simple-git commands similar to those in git in a terminal:
![Screenshot 2019-06-12 22 52 48](https://user-images.githubusercontent.com/12837282/59407052-f220e980-8d64-11e9-9f17-7726e5a9b189.jpg)

So, if we were to use the git log function in simple-git, we could possibly make a command like `git log --branches --not --remotes`, which would give us a list of the commit IDs currently not on the remote branch (i.e. local un-pushed commits):
![Screenshot 2019-06-12 22 22 05](https://user-images.githubusercontent.com/12837282/59407115-20062e00-8d65-11e9-9882-bf1d743ef62e.jpg)

**Comment by colinwerner** [comment]
@trstndvll, yes you can! Although I haven't figured out exactly how it works I can get the basic functionality to work:
ie 'git stash show'

**Comment by colinwerner** [comment]
Furthermore, @trstndvll you can do this:
sGitRepo.silent(true).stash(["show", "stash@{4}"]).then((result)=> {
which equates to 'git stash stash@{4}'

Hope this helps.

**Comment by aeogunmuyiwa** [comment]
sGitRepo.silent(true).log(["@{u}.."]).then((result)=> {
    for(var i = 0 ; i < result.all.length; i++){
      console.log(result.all[i].hash);
    }

    }).catch(function(err) {
    console.log(err);
    });

would return the commit id of the ahead, but I am unsure how to identify them while the graph is being made

**Comment by Unimax** [comment]
found an initial solution. but need to refresh the graph manually once (because the local commit count is not available asap but the graph gets loaded). It will update as you pull, push or commit.

use this to chose your color https://color.adobe.com/create/color-wheel/
I have listed in a comment another idea to solve our problem. i.e. to compare hash
do check https://visjs.org/docs/network/nodes.html for possible options of modifying a node

**Comment by aeogunmuyiwa** [comment]
@Unimax  I have fixed the issue of having to refresh the graph manually. This was done by switching the functionality to use the commit id hash of the ahead and storing them in an array before processing the graph.

**Comment by aeogunmuyiwa** [comment]
Also Fixed the issue of updating the highlight of the graph after a push has been made.

**Comment by Unimax** [comment]
Refactor and chain the processGraph after updating the unpushCommitList. This will make sure whenever graph is updated unpushCommitList updated first.
The previous solution had a chance of updating the list after the graph is plotted.
