### ISSUE TITLE
Loading bar does not go away when failing to clone a repo

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#16]
The loading bar that appears at the bottom of the navigation section does not disappear after failing to clone a repo, even if a new repo is opened.

**Steps to reproduce:**
1. Continue without signing in
![loading-bar1](https://user-images.githubusercontent.com/31779196/59533655-07029780-8ea1-11e9-8ad0-f2bc48dcd370.png)
2. Clone a private repo (this should fail). Notice the loading bar still loads at the bottom of the navigation section.
![loading-bar2](https://user-images.githubusercontent.com/31779196/59533671-1386f000-8ea1-11e9-8395-7e3f3db7fdbc.png)
3. Load or clone any other repo.
![loading-bar3](https://user-images.githubusercontent.com/31779196/59533730-37e2cc80-8ea1-11e9-83ac-f02510461214.png)
The loading bar still appears and won't go away on refresh.

**Expected behaviour**
The loading bar disappears, or does not appear at all, upon a failed clone.

**Comment by omazhary** [comment]
Couldn't reproduce because of an issue with sign out not working correctly.
Will investigate this sign out issue further

**Comment by hdauvic** [comment]
> Couldn't reproduce because of an issue with sign out not working correctly.
> Will investigate this sign out issue further

Unsure if the sign out issue has been resolved, however the behaviour is now reproducible. I've updated the issue accordingly.
