### ISSUE TITLE
Edit/Delete the Upstream in One Command

### ISSUE THREAD

**Issue by roweba** [uvicgse/project-virtual-team-1#172]
Currently when editing the upstream repository, the user has to enter the url of the new upstream and then click confirm. However, if an upstream is already configured then an error is thrown. The user has to manually delete the upstream themselves before adding a new one. A user should be able to enter the address of the new upstream, and then a modal should appear that says "Upstream already exists, do you want to replace with {url}?" and the user will cancel or confirm.

**Comment by colinwerner** [comment]
Consider pre-populating the edit field with the currently set repo?

**Comment by roweba** [comment]
I don't think this is necessary, as the current repo is already displayed.

**Comment by colinwerner** [comment]
I'm just thinking it might be nice to edit the repo, say perhaps I have a typo?

**Comment by roweba** [comment]
Good point, I guess the main reason someone would want to edit the upstream is to fix a typo
