### ISSUE TITLE
Rework colours for unpushed commits

### ISSUE THREAD

**Issue by trstndvll** [uvicgse/project-virtual-team-1#178]
Change the colours for the unpushed commit highlight to visually relate to the ahead behind badges on the right hand side. So, the node highlight should be the same colour of the ahead badge, and the pull button hover colour should be the same colour as the behind badge.

**Comment by aeogunmuyiwa** [comment]
<img width="1183" alt="Screen Shot 2019-06-19 at 9 33 28 PM" src="https://user-images.githubusercontent.com/25914907/59818837-577f5800-92da-11e9-857a-93e2971a4400.png">

- Currently the ahead commit badge matched the ahead highlight of the graph

**Comment by aeogunmuyiwa** [comment]
PR approved and merged into master
