### ISSUE TITLE
Use Oauth instead of storing the username and password in data.json

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#19]
Saving the token from Github's Oauth would be more secure than storing a encrypted password in data.json.

**Comment by Athenasko** [comment]
Based on a preliminary search, this feature should require the secure storing of Oauths, and the deletion of the old passwords and methods of storing it.
(https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#non-web-application-flow and https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/)

**Comment by colinwerner** [comment]
I suggest we have a research task this sprint to research this issue and push this to Sprint 2.

**Comment by norrisng** [comment]
@dragonprevost and I have agreed that we're no longer using separate issues as subtasks to this parent issue. Details will be documented in the comments here as necessary.

There's too many little details peppered everywhere (e.g. use of username/password fields) that makes it hard to define a subtask without sounding overly miniscule/specific.
