### ISSUE TITLE
Upgrade Angular 2 to Angular 8

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#24]
**Feature Request:**

Currently the application is running on Angular 2, an upgrade to Angular 7 would help make future development easier due to more community support for it and also app performance of the application will be better with Angular 7.

**Comment by jpstoldt** [comment]
Upgrading this early in the project is also expected to help accelerate development of user interface features/issues in later sprints

**Comment by jpstoldt** [comment]
Added Wiki page to describe the steps required for the upgrade towards Angular 8 https://github.com/uvicgse/project-virtual-team-1/wiki/Research:-Future-Upgrade-Instructions-for-VisualGit-towards-Angular-8

**Comment by mehrler12** [comment]
Though the upgrade to Angular 8 couldn't happen, as much work as possible towards the goal has occurred in #83 , this was accepted as an alternate solution by the PO so this is closed.
