### ISSUE TITLE
Can't see file navigator when opening a repo without logging in (Ubuntu 18.04.1 LTS)

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#27]
The file navigator is unreadable if the open button is clicked,without being logged in.
_NOTE: This bug is only reproducible on Ubuntu/Linux systems so far_

**Steps to reproduce:**
1. Run the application
2. Click "Continue without sign in"
3. Click "Open"
![image](https://user-images.githubusercontent.com/22312351/57663353-85b99b80-75a8-11e9-8817-eae90588c650.png)

**Expected behaviour:**
![image](https://user-images.githubusercontent.com/22312351/57663369-9407b780-75a8-11e9-8cb7-466f3f32b12e.png)

**Comment by Unimax** [comment]
I also had this issue but after upgrading node. no longer have this issue.
![working](https://user-images.githubusercontent.com/4117562/59831676-1c3f5200-92f7-11e9-9c30-b02320850440.png)

closing due to suspect resolve with node upgrade.
