### ISSUE TITLE
Investigate white nodes

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#29]
After making a commit, white nodes appear on the graph next to the node containing the commit. These white nodes don’t serve any discernible purpose and should be either removed or better labelled.

![image](https://user-images.githubusercontent.com/22312351/57663561-56eff500-75a9-11e9-9b8c-8a3bb6cef969.png)

**Comment by sterlinglaird** [comment]
Related to #101. The issue seems to have gotten more severe since this issue was made since the white nodes alter the graph itself instead of just appearing randomly
