### ISSUE TITLE
Add stashing and reapplying functionality

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#34]
Add support for stashing and reapplying changes, so that users can store their changes without committing and move on to another branch. The user should be able to view what changes are stashed on what branches

**Comment by colinwerner** [comment]
Decomposed into:
#86: Allow a user to stash changes
#87: Allow a user to view a list of stashed changes
#88: Allow a user to pop from the list of stashed changes

**Comment by colinwerner** [comment]
#106: allow a user to stash untracked files

**Comment by colinwerner** [comment]
Removing this from Sprint 3, as we continue to decompose it.
