### ISSUE TITLE
Add functionality for syncing changes between a fork and the original 

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#36]
When you fork a repository the repo doesn't automatically keep up with changes made to the master branch in the original, it has to be synced from the upstream repository. It would be useful for VisualGit to have this functionality when you fork from a repo.

**Comment by colinwerner** [comment]
There are actually a number of ways to keep a repository up to date. I'd recommend:
https://help.github.com/en/articles/fork-a-repo
https://help.github.com/en/articles/syncing-a-fork

Thus we should probably break this feature down:
1.) add the ability for the user to see 'git remote -v' (not sure if nodegit supports this) (this will show the remote repository)
2.) add the ability to edit the remote repository (ie 'git remote add upstream https://...git'
3.) add the ability for the user to fetch with options ('git fetch upstream') -- this might need to be decomposed as well
4.) add the ability for the user to merge with options (git merge upstream/master) -- this might need to be decomposed as well.

**Comment by roweba** [comment]
> There are actually a number of ways to keep a repository up to date. I'd recommend:
> https://help.github.com/en/articles/fork-a-repo
> https://help.github.com/en/articles/syncing-a-fork
> 
> Thus we should probably break this feature down:
> 1.) add the ability for the user to see 'git remote -v' (not sure if nodegit supports this) (this will show the remote repository)
> 2.) add the ability to edit the remote repository (ie 'git remote add upstream https://...git'
> 3.) add the ability for the user to fetch with options ('git fetch upstream') -- this might need to be decomposed as well
> 4.) add the ability for the user to merge with options (git merge upstream/master) -- this might need to be decomposed as well.

Good decomposition of the issue, I feel like adding the remote repository and syncing the fork definitely need to be separated. I don't think steps 3-4 need to be decomposed though, these are all just steps in syncing the fork to the local master.

**Comment by colinwerner** [comment]
Pushed to Sprint 3. Issue #73 has been created to perform research in Sprint 2.

**Comment by roweba** [comment]
This issue has been decomposed into issue #95  and #96
