### ISSUE TITLE
Add tagging support

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#39]
**Feature request:**

Add support for tagging commits in the past and/or the current commit that has yet to be pushed. This will allow users to mark important points in their repository for example "v1.0" without needing to search for a certain commit message/checksum. Users should also be able to view the tags on the main page

**Comment by colinwerner** [comment]
The tagging feature should probably be broken down into separate chunks (https://git-scm.com/book/en/v2/Git-Basics-Tagging):
1.) view current tags in repo (git log)
2.) search current tags in repo (git log -l "v1.0")
2.) create a new tag (two different types) (git tag -a v1.4 -m "my version 1.4" and git tag v1.4-lw)
3.) showing existing tags associated with commits
4.) add a tag to a commit
5.) delete a tag from the repo

**Comment by jerushachua** [comment]
This issue will be decomposed into the above issues and we will push out all issues except one.

**Comment by jerushachua** [comment]
The first issue will be assigned to group 1.

**Comment by hdauvic** [comment]
This feature addition is scheduled to be completed in Sprint 4.

**Comment by jerushachua** [comment]
Closing as the remaining issues related to tagging have their own documentation.
