### ISSUE TITLE
Repeating "navbar" console log messages when in repo

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#4]
When in a repo the console log repeats the same vague lines continually. These make it difficult to debug issues in the code or to understand what is going on.

**Steps to reproduce:**
1. Open a repo, let it sit for a few seconds.
2. Review the console.
![navbar](https://user-images.githubusercontent.com/31779196/59477424-00751100-8e0a-11e9-8aec-310b7e4aae1d.png)

**Expected behaviour:**
The log messages could either be disabled or made more meaningful.

**Comment by Unimax** [comment]
this issue no longer happens. can anyone confirm this and close this?

**Comment by hdauvic** [comment]
> this issue no longer happens. can anyone confirm this and close this?

I can confirm that it still occurs. I believe it has to do with the refreshing of the program being done in specific intervals to keep a live update of the content.

**Comment by hdauvic** [comment]
I've found the source of the `nav class` print out. It is currently unnecessary for debugging so I've commented it out, with an additional comment explaining why. This will change will be pushed with the changes in #176 .
