### ISSUE TITLE
Unable to see edited files (staged or unstaged) in visualgit

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#47]
When I make a change to a local repo (whether staged or not), I am unable to see the edited files in the repo.

Steps to reproduce:
1.) Open local repo
2.) Edit a file
3.) Save, Close

Expected Steps:
4.) the edited file should be visible

Actual Steps:
4.) the edited files are not visible

![image](https://user-images.githubusercontent.com/15122789/58147210-475a5700-7c0e-11e9-82ef-db672c494a45.png)

**Comment by colinwerner** [comment]
This is related to #48.

**Comment by colinwerner** [comment]
Actually I can see the staged/unstaged files (well some of them) when there are more than one.

Also, this issue seems specific to Mac.

**Comment by jerushachua** [comment]
This issue will be assigned to group 4.

**Comment by colinwerner** [comment]
I can fix the initial issue. However, there appears to be another issue whereby files staged via command line are not recognized in visual git. *humpf*

Here's the diff for anyone who wants to look.
[diff.txt](https://github.com/uvicgse/project-virtual-team-1/files/3210468/diff.txt)

**Comment by colinwerner** [comment]
My changes are in issue-#47-unable-to-see-edited-files -- we can look at the staged vs non-staged issue later.
