### ISSUE TITLE
Research implementing OAuth for the project

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#57]
This task is to research #19 to implement OAuth for Virtual Git.

**Comment by jtiz003** [comment]
From sprint 1 negotiation: This issues will be investigated in sprint 1, with the intention to complete it in sprint 2.

**Sprint 1 objectives:**
- Build knowledge of the relevant parts of the application.
- Have a clear plan of how to implement this. 
- Provide time estimates for the required work
- (Optional) Begin implementation.

**Comment by jtiz003** [comment]
@colinwerner Was the research for this issue documented somewhere? My preference would be for findings related to an issues to be commented directly onto the issue.

**Comment by colinwerner** [comment]
It's on our wiki. I'll have it copied here as well.

**Comment by jtiz003** [comment]
@colinwerner Ah thanks, looks good! 
A link to the wiki here is probably sufficient also.
Just make it easy for me to see what you did :)

**Comment by dragonprevost** [comment]
@jtiz003 You can find our research [here](https://github.com/uvicgse/project-virtual-team-1/wiki/Oauth2-Research). There has also been a few changes to the codebase on this issue in the last sprint.

**Comment by norrisng** [comment]
For some reason, this issue wasn't closed even though it was completed during Sprint 1. Closed now!
