### ISSUE TITLE
Feature request: Show most recent repositories

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#6]
Implement a feature into VisualGit which shows the users most recent (maybe recent 5?) opened repositories, and lets them open them.

**Comment by Athenasko** [comment]
This feature can be probably be broken down into two parts based on a brief search (https://tutorialedge.net/javascript/angularjs/angularjs-store-cookies-tutorial/ and https://docs.worldsecuresystems.com/user-manual/e-Commerce/Products/adding-a-viewed-product-history):

1. Creating and storing the cookie or repository information.
2. Displaying and Viewing the last X repositories / Loading a selected repository. (This could further be broken down if desired).

**Comment by sterlinglaird** [comment]
This would make the issue larger. But maybe the most recent repositories list should be persistent through opening and closing the application? I feel like the usefulness is diminished when the list only contains repos in the current VisualGit session.

**Comment by nikola-rados** [comment]
@sterlinglaird I agree with your comment.  If I have time once I've finished the main issue I can look into it. 👍
