### ISSUE TITLE
Allow a user to checkout a tag

### ISSUE THREAD

**Issue by sterlinglaird** [uvicgse/project-virtual-team-1#61]
In git, tags can be checked out just like branches. We should support this feature.

**Comment by sterlinglaird** [comment]
To make this more interactive we could actually just do a right click, on any commit not and have a checkout button since really you can checkout any commit.

**Comment by SiRumCz** [comment]
@sterlinglaird This is a good idea. But since we are trying to keep our last sprint as lightweight as possible, I suggest you to create a new issue about this feature for future students.

**Comment by sterlinglaird** [comment]
@SiRumCz Yea totally. I just made #191
