### ISSUE TITLE
Initialize octonode for Oauth Token

### ISSUE THREAD

**Issue by dragonprevost** [uvicgse/project-virtual-team-1#68]
Sub task to issue #19 
* Octonode initializes a users credential with a username and password. Since the application only has access to an access token, a new method for initializing a users credentials must be implemented.
* If any other octonode calls need username or password they will also need to be updated.

**Comment by norrisng** [comment]
No longer using subtasks for parent #19.

Refer to https://github.com/uvicgse/project-virtual-team-1/issues/19#issuecomment-497881574 for details.
