### ISSUE TITLE
Update nodegit for Oauth Token

### ISSUE THREAD

**Issue by dragonprevost** [uvicgse/project-virtual-team-1#69]
Sub task to issue #19

* nodegit is initialized with a users, username and password. This will need to be updated for the new Oauth token
* All other nodegit calls that require a username or password will have to be updated to receive an access token instead.

**Comment by norrisng** [comment]
No longer using subtasks for parent #19.

Refer to https://github.com/uvicgse/project-virtual-team-1/issues/19#issuecomment-497881574 for details.
