### ISSUE TITLE
Pushing or pulling twice will crash application

### ISSUE THREAD

**Issue by trstndvll** [uvicgse/project-virtual-team-1#71]
This is an extension of issue #30 , where pushing or pulling the application twice in a row will crash the application. We also want to add error handling to the push function as there is currently none, this is being handled in #72 .

**Comment by trstndvll** [comment]
Adding the comments from @Unimax for issue #30:

I found out that the application is crashing because of the 'cred' object we are using for authentication in a callback if failing due to one of the following reason:

it's not able to create the credential object in the C layer. (at least for the 2nd time) .becuase with some changes i was able to see the exact error as in the issue nodegit/nodegit#982
because we are reusing the object it maybe expires after one use and hence having an issue. not sure why.
to prove that is the issue we can simply (I tested on Windows 10 and Ubuntu 18.04)
change the line 406 in master, or 416 in the issue30 branch i.e.
return cred;
into
return Git.Cred.userpassPlaintextNew("username", "password"); 
Note: for now use your username and password. or can use getUsernameTemp() and getPasswordTemp() function from the authenticate.ts

Possible Solutions:

I notice that we are using nodegit instead of Git in some places to generate the cred object. so we can change it to Git. more details on that nodegit/nodegit#982
it will be fixed with the Oauth changes.
On further notes:
Current Flag 'pushButNoCommit' solves an application level optional choice that we want to let the user try to push without any local commits or not. I would say yes (should allow), especially when we don't have any way to detect any local commit done before the start of the application. (by command line or by the same application). Also because with the Auth fixed, it won't crash the application even if you push with no local commits. (tested!!)

moreover, we need to add error handling in case of push actually fails. current flow marks it successful even when it actually fails.

also on linux, i have another issue with the branch name coming as "Branch: master" instead of "master" which I fixed by changing the line 391 (master) . (on Windows this was not a problem)
let branch = document.getElementById("branch-name").innerText.split(": ")[1];

**Comment by colinwerner** [comment]
@Unimax: I saw the "Branch:Master" issue as well, I thought that might be part of the problem, but it didn't resolve anything.

What I was confused by is I see these two commands:
396: addCommand("git push -u origin " + branch);
...
401: return remote.push(

Are we pushing twice?

**Comment by Unimax** [comment]
'Branch: ' got fixed by one who caused it :)
this issue is merged.. Closing.

**Comment by Unimax** [comment]
> addCommand("git push -u origin " + branch);
@colinwerner 
add Command is just to print on screen :)
