### ISSUE TITLE
Research Issue #36: Add functionality for syncing changes between a fork and the original

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#73]
Research Issue #36.

**Comment by colinwerner** [comment]
In git.ts there is a function called fetchFromOrigin that can be invoked from the hamburger menu, while this menu shows the git commands in the terminal, it does not actually do anything.

**Comment by roweba** [comment]
James suggested that there be two buttons for this feature, one that sets up the upstream repository and one that syncs. The upstream address should be saved the first time it is entered so the user doesn't have to enter it every time they want to sync. Every time the sync button is pressed it should sync from this saved repository. The user should be able to edit the address of the upstream repository.

**Comment by subahm** [comment]
Do we want to divide this in to 2 different issues: upstream and sync and tackle both of them in sprint 3?

**Comment by roweba** [comment]
Yeah we should

**Comment by colinwerner** [comment]
Please link the issues here for James to reference.

**Comment by colinwerner** [comment]
Actually, if you feel like the research is done and you know what you need to do for sprint 3 (and are confident in completing it, please link the issues in the original #36 -- then close both this issue (#73) and the original (#36).

**Comment by subahm** [comment]
This issue is decomposed into two different issues: #95 and #96, which will be implemented in Sprint 3
