### ISSUE TITLE
Unclear error message when trying to login while not connected to internet

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#9]
When you try to login while not connected to the internet, the error message is not very helpful. There should be a clearer error message.

**Steps to reproduce:**
1. Disconnect from the internet.
2. Attempt to sign in. 

![image](https://user-images.githubusercontent.com/22312351/57647019-0e225580-7616-11e9-977b-a7ff175425c5.png)

**Comment by colinwerner** [comment]
Are there any pre-requisites to this issue? When I turn my internet off and try to log in, I see:

![image](https://user-images.githubusercontent.com/15122789/58148326-319b6080-7c13-11e9-96ca-9106a8309e40.png)

**Comment by colinwerner** [comment]
Apparently this issue is reproducible on Windows.
